from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class AgentEventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    CLONE_STARTED = "CLONE_STARTED"
    CLONE_COMPLETED = "CLONE_COMPLETED"
    CLONE_FAILED = "CLONE_FAILED"
    PROJECT_ANALYSIS_STARTED = "PROJECT_ANALYSIS_STARTED"
    PROJECT_ANALYSIS_COMPLETED = "PROJECT_ANALYSIS_COMPLETED"
    PROJECT_ANALYSIS_FAILED = "PROJECT_ANALYSIS_FAILED"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    FINDING_CREATED = "FINDING_CREATED"
    ISSUE_GROUP_CREATED = "ISSUE_GROUP_CREATED"
    FIX_PLAN_CREATED = "FIX_PLAN_CREATED"
    RISK_ASSESSED = "RISK_ASSESSED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    PATCH_APPLIED = "PATCH_APPLIED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    VERIFICATION_PASSED = "VERIFICATION_PASSED"
    SELF_CORRECTION_STARTED = "SELF_CORRECTION_STARTED"
    SELF_CORRECTION_COMPLETED = "SELF_CORRECTION_COMPLETED"
    REGRESSION_TEST_STARTED = "REGRESSION_TEST_STARTED"
    REGRESSION_TEST_PASSED = "REGRESSION_TEST_PASSED"
    REGRESSION_TEST_FAILED = "REGRESSION_TEST_FAILED"
    PEER_REVIEW_STARTED = "PEER_REVIEW_STARTED"
    PEER_REVIEW_APPROVED = "PEER_REVIEW_APPROVED"
    PEER_REVIEW_CHANGES_REQUESTED = "PEER_REVIEW_CHANGES_REQUESTED"
    PEER_REVIEW_REJECTED = "PEER_REVIEW_REJECTED"
    PEER_REVIEW_COMPLETED = "PEER_REVIEW_COMPLETED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    HUMAN_CHANGES_REQUESTED = "HUMAN_CHANGES_REQUESTED"
    MEMORY_CAPTURE_STARTED = "MEMORY_CAPTURE_STARTED"
    MEMORY_CAPTURE_COMPLETED = "MEMORY_CAPTURE_COMPLETED"
    GIT_FINALIZATION_STARTED = "GIT_FINALIZATION_STARTED"
    GIT_BRANCH_CREATED = "GIT_BRANCH_CREATED"
    GIT_COMMIT_CREATED = "GIT_COMMIT_CREATED"
    GIT_PUSH_COMPLETED = "GIT_PUSH_COMPLETED"
    GIT_PR_CREATED = "GIT_PR_CREATED"
    GIT_FINALIZATION_COMPLETED = "GIT_FINALIZATION_COMPLETED"
    GIT_FINALIZATION_FAILED = "GIT_FINALIZATION_FAILED"
    REPORT_GENERATION_STARTED = "REPORT_GENERATION_STARTED"
    REPORT_GENERATION_COMPLETED = "REPORT_GENERATION_COMPLETED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"


class AgentEvent(BaseModel):
    """Persisted workflow event emitted during autonomous run orchestration."""

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(alias="_id")
    run_id: str
    event_type: AgentEventType
    stage: str
    agent: str | None = None
    tool: str | None = None
    status: str = "ok"
    message: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime

    @classmethod
    def from_document(cls, document: dict) -> "AgentEvent":
        document = document.copy()
        document["_id"] = str(document["_id"])
        document["run_id"] = str(document["run_id"])
        return cls.model_validate(document)
