"""Build informative pull request descriptions from run artifacts."""

from __future__ import annotations

from dataclasses import dataclass

from app.models.fix_attempt import FixAttempt
from app.models.patch_plan import PatchPlan
from app.models.peer_review_result import PeerReviewResult
from app.models.self_correction_cycle import SelfCorrectionCycle
from app.models.verification_result import VerificationResult


@dataclass(frozen=True)
class PullRequestDescriptionContext:
    patch_plans: list[PatchPlan]
    fix_attempts: list[FixAttempt]
    verification_results: list[VerificationResult]
    peer_reviews: list[PeerReviewResult]
    self_correction_cycles: list[SelfCorrectionCycle]
    changed_files: list[str]


def build_pull_request_title(patch_plans: list[PatchPlan], run_id: str) -> str:
    if not patch_plans:
        return f"CodeThera automated remediation ({run_id[:8]})"
    primary = sorted(patch_plans, key=lambda plan: plan.priority_rank)[0]
    return f"CodeThera: {primary.title}"


def build_pull_request_description(context: PullRequestDescriptionContext) -> str:
    sections = [
        "## Problem",
        _problem_section(context.patch_plans),
        "## Root Cause",
        _root_cause_section(context.patch_plans),
        "## Changes",
        _changes_section(context.changed_files, context.patch_plans),
        "## Tests",
        _tests_section(context.patch_plans),
        "## Verification",
        _verification_section(context.verification_results),
        "## Peer Review",
        _peer_review_section(context.peer_reviews),
        "## Self-Correction",
        _self_correction_section(context.self_correction_cycles),
        "## Risk",
        _risk_section(context.patch_plans),
    ]
    return "\n\n".join(section for section in sections if section)


def build_branch_name(run_id: str, patch_plans: list[PatchPlan]) -> str:
    slug = "remediation"
    if patch_plans:
        primary = sorted(patch_plans, key=lambda plan: plan.priority_rank)[0]
        slug = _slugify(primary.title)
    return f"agent/{run_id[:12]}-{slug}"[:80]


def _problem_section(patch_plans: list[PatchPlan]) -> str:
    if not patch_plans:
        return "Automated remediation generated by CodeThera."
    lines = [f"- {plan.title}" for plan in patch_plans[:5]]
    return "\n".join(lines)


def _root_cause_section(patch_plans: list[PatchPlan]) -> str:
    if not patch_plans:
        return "See attached diagnostics."
    return "\n".join(f"- {plan.root_cause}" for plan in patch_plans[:5])


def _changes_section(changed_files: list[str], patch_plans: list[PatchPlan]) -> str:
    file_lines = [f"- `{path}`" for path in changed_files[:20]]
    rationale_lines = [
        f"- {plan.title}: {plan.solution_rationale}" for plan in patch_plans[:5]
    ]
    parts = []
    if file_lines:
        parts.append("\n".join(file_lines))
    if rationale_lines:
        parts.append("\n".join(rationale_lines))
    return "\n".join(parts) if parts else "No file changes recorded."


def _tests_section(patch_plans: list[PatchPlan]) -> str:
    tests: list[str] = []
    for plan in patch_plans:
        tests.extend(plan.expected_tests)
    if not tests:
        return "Targeted verification commands executed during the run."
    return "\n".join(f"- `{test}`" for test in sorted(set(tests))[:10])


def _verification_section(verification_results: list[VerificationResult]) -> str:
    if not verification_results:
        return "Verification results were not recorded."
    return "\n".join(
        f"- {result.patch_plan_id}: {result.status.value}"
        + (f" ({result.failure_summary})" if result.failure_summary else "")
        for result in verification_results[:10]
    )


def _peer_review_section(peer_reviews: list[PeerReviewResult]) -> str:
    if not peer_reviews:
        return "Peer review was not required for this run."
    return "\n".join(
        f"- {review.patch_plan_id}: {review.verdict.value} — {review.synthesis_summary}"
        for review in peer_reviews[:5]
    )


def _self_correction_section(cycles: list[SelfCorrectionCycle]) -> str:
    if not cycles:
        return "No self-correction cycles were required."
    return "\n".join(
        f"- {cycle.patch_plan_id}: {cycle.status.value} — {cycle.failure_summary}"
        for cycle in cycles[:5]
    )


def _risk_section(patch_plans: list[PatchPlan]) -> str:
    if not patch_plans:
        return "Risk was assessed during planning."
    return "\n".join(
        f"- {plan.title}: {plan.estimated_risk.value}" for plan in patch_plans[:5]
    )


def _slugify(value: str) -> str:
    slug = "".join(character.lower() if character.isalnum() else "-" for character in value)
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")[:40] or "remediation"
